"""Generate v191 (ss-MGOT) and v192 (Alsop) PPLs from the verified v18 source.

Single source of truth for both method paths.  Replaces the superseded
examples/build_v191.py and examples/build_v192.py.  Every insertion is anchored
on an exact, unique line of the verified v18 file; the v18 control path is
otherwise untouched (see examples/audit_v19_source.py).

Run:  python examples/build_v19_ppl.py
"""
from __future__ import annotations

import hashlib
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
V18 = ROOT / "scanner/FSE_dwi_CPMG_non_CPMG_twoTE-1.8.ppl"
V18_SHA = "3b420376331e918b4c864e9b37937ef35fd9f49066b8d6402e44aae9da598db2"
OUT = {"ssmgot": ROOT / "scanner/FSE_dwi_CPMG_non_CPMG_twoTE-1.91.ppl",
       "alsop": ROOT / "scanner/FSE_dwi_CPMG_non_CPMG_twoTE-1.92.ppl"}

# Pulse constants derived from docs/v19/reference_rf/real_rf_transfer_results.json
# (fitted RF-time-only compensation / net RF-time gradient area) and
# docs/v19/rf_library_manifest.json (inferred rfcal scale numerators).
RF = {
    # name: (rfnum, frame, duration_us, tbw_x100, kappa_x10000, rfcal_numerator)
    "ex": (18, "v19_slrprep90", 3200, 355, 5316, 3436),
    "rf": (19, "v19_slrprep180", 3200, 355, 5000, 11509),
    "tip": (20, "v19_slrtip90", 3200, 355, 5318, 3761),
    "elim": (21, "v19_slrelim90", 3200, 355, 5309, 3761),
    "re": (22, "v19_reexc90", 1200, 154, 5547, 5392),
    "im": (23, "v19_imaging180", 1200, 154, 5000, 10783),
}


def kappa_check():
    r = json.loads((ROOT / "docs/v19/reference_rf/real_rf_transfer_results.json").read_text())["pulses"]
    m = json.loads((ROOT / "docs/v19/rf_library_manifest.json").read_text())["pulse_frames"]
    for key, (_, frame, dur, tbw, kap, num) in RF.items():
        p = r[frame]
        k = -p["post_RF_correction_cycles_m"] / p["net_RF_gradient_cycles_m"]
        assert abs(round(k * 10000) - kap) <= 1, (frame, k)
        assert m[frame]["rfcal_scale_numerator"] == num, frame
        assert abs(m[frame]["duration_us"] - dur) < 1e-9 and abs(m[frame]["TBW"] * 100 - tbw) < 1e-6


HEADER = {
    "ssmgot": """/* V191 ss-MGOT DIFFUSION-PREPARED FSE -- SOURCE IMPLEMENTATION, NOT COMPILED.
   Gibbons et al. MRM 2018 mechanism: slab-selective diffusion preparation, added
   slice dephasing, selective tip-up storing the MG component on Mz, transverse
   spoiler (phase axis), slice-selective re-excitation, CPMG train with +D recall
   before / -D restoration after every ADC. Method only; v18 is the control.
   RF: local research libraries v19_*.seq, one per pulse (real SLR / Hamming-sinc
   pulses). Water-only spatial tip-up: NOT Gibbons' spectral-spatial pulse.
   Generated by examples/build_v19_ppl.py; see docs/v19/README.md. */
""",
    "alsop": """/* V192 ALSOP DIFFUSION-PREPARED FSE -- SOURCE IMPLEMENTATION, NOT COMPILED.
   Alsop MRM 1997 mechanism: diffusion preparation, added slice dephasing,
   selective 90-degree elimination pulse on the refocusing axis (MG retained
   transverse, quadrature sent to Mz), tailored low-angle CPMG train with +D
   recall before / -D restoration after every ADC. No storage/spoiler/re-
   excitation. Method only; v18 is the control. RF: local research
   libraries v19_*.seq, one per pulse. Generated by examples/build_v19_ppl.py. */
""",
}

# One WavEd library per research pulse (examples/build_v19_rf_library.py), so each
# frame carries its own user() expression and embedded samples like opt90_as.seq.
USE_LINE = "".join(f'#use RF1 "g:\\J_Figger\\seqlib\\{frame}.seq" pf{n}\n'
                   for (n, frame, _, _, _, _) in RF.values())

PARAMS_COMMON = '''SCROLLBAR "V19 method ON","method-only PPL: must be 1","%d",0,1,1,1,v19_on;
EDITTEXT  "V19 added dephasing","cycles across imaging slice","%d",1,8,2,1,v19_cycles;
EDITTEXT  "V19 compensation lobe flat","us, multiple of tramp/50","%d",100,5000,1000,1,v19_comp_flat;
VAR_ARRAY "V19 refocusing flips","0.1 deg; entry 0 = imaging RF 1","%d",1,1800,1,v19_flip_tenths,64,1800;
'''
PARAMS_SSMGOT = '''EDITTEXT  "V19 prep slab width","per mille of imaging slice","%d",1000,10000,3000,1,v19_slab_pml;
EDITTEXT  "V19 tip-up width","per mille of imaging slice","%d",1000,10000,1667,1,v19_tip_pml;
EDITTEXT  "V19 spoiler moment","cycles/mm on phase axis","%d",1,200,32,1,v19_spoil_cpmm;
EDITTEXT  "V19 spoiler amplitude","DAC on phase axis","%d",1000,32767,16384,1,v19_spoil_dac;
'''

DECL_COMMON = '''	// [V19-DECL] method variables (v19_on=0 leaves all of them unused)
	int v19_on, v19_cycles, v19_comp_flat, v19_mode;
	int v19_flip_tenths[64];
	int v19_error_code;
	int v19_gabs, v19_gsign, v19_i, v19_setup_ticks;
	int v19_g_ex, v19_g_rf, v19_g_m, v19_g_im, v19_c_ex, v19_c_m, v19_d_dac, v19_rp_dac;
	int v19_mul_ex, v19_mul_rf, v19_mul_m;
	int v19_l_ex, v19_l_rf, v19_l_diff, v19_l_d, v19_l_m, v19_l_mr, v19_l_im;
	int v19_f_ex, v19_f_rf, v19_f_m, v19_f_im, v19_diff_flat, v19_mr_zero;
	long v19_r, v19_rd, v19_ld, v19_te_us, v19_esp_us, v19_tacq_half, v19_t0;
	long v19_s_ex, v19_s_rf, v19_a1, v19_a2, v19_s_d, v19_s_m, v19_s_1, v19_e_1;
	long v19_b_ex, v19_b_rf, v19_b_df, v19_b_d, v19_b_m, v19_b_im, v19_len;
	long v19_gap_x1, v19_gap_1r, v19_gap_r2, v19_gap_2d, v19_gap_dm;
	long v19_go_ex, v19_off_ex, v19_rem_ex, v19_go_rf, v19_off_rf, v19_rem_rf;
	long v19_go_m, v19_off_m, v19_rem_m, v19_go_im, v19_off_im, v19_rem_im;
	long v19_lead, v19_wait_next, v19_first_wait, v19_gap_ir, v19_rd_a1, v19_rd_a2;
	long v19_adc_mid, v19_post_a, v19_post_b, v19_post_end, v19_df_wait, v19_shot_us;
	long v19_read_len, v19_nsp, v19_unblank, v19_offl_ex, v19_offl_rf, v19_offl_m, v19_offl_im;
'''
DECL_SSMGOT = '''	int v19_slab_pml, v19_tip_pml, v19_spoil_cpmm, v19_spoil_dac;
	int v19_g_re, v19_c_re, v19_mul_re, v19_l_sp, v19_l_re, v19_l_rr, v19_f_re, v19_t_sp;
	long v19_s_sp, v19_s_re, v19_b_sp, v19_b_re, v19_gap_ms, v19_gap_sr;
	long v19_go_re, v19_off_re, v19_rem_re, v19_offl_re;
'''

NEWSHAPE = "\n".join(
    f'\tNEWSHAPE_MAC({n}, pf{n},"{frame}" , {dur}, {round(tbw*10000/dur)}) // [V19] research RF; exact BW {tbw*10000/dur:.3f} Hz'
    for (n, frame, dur, tbw, _, _) in RF.values()) + "\n"

# ---------------------------------------------------------------- macros
MACROS = r'''
// [V19-MACROS] Method timing primitives. Times in 0.1-us ticks are long.
// V19_TAIL_US: tail window for SetList/SelectMatrix/phase() (phase ~29 us,
// EVO manual 3.3.1.11). V19_GAP_MIN: minimum delay32 gap. V19_ANCHOR: estimated
// statement-transition cost between a waittimer/delay32 exit and the next
// starttimer entry (0.5 us = documented starttimer duration, manual 4.6; the
// true value needs a compiler/console trace). V19_INIT_COST: initiate() 7.6 us
// (manual 3.3.2 table).
#define V19_TAIL_US 100L
#define V19_GAP_MIN 20L
#define V19_ANCHOR 5L
#define V19_INIT_COST 76L
// Timer counts 0..49999 (5 ms): every waittimer must be ISSUED and TARGETED
// below ~4.9 ms after its starttimer (manual p90; v18 uses <= 47975 ticks).
#define V19_MAX_WAIT 49000L
// Post-initiate calculation window: same budget as v18 (8997 ticks; v18
// comment measures 8236). Holds CREATE_MATRIX + three long divisions.
#define V19_ADC_SLOW 8997L
// Pad after rfon(0)+PDD mask before re-anchoring (ticks); covers ~10 statements.
#define V19_POST_RF 200L
// Real-RF calibration: board multiplier = scale(rfcal, numerator, 10000)
// (inferred linear DAC x multiplier model, docs/v19/rf_library_manifest.json)
#define V19_SELECTOR(dest, tbw100, t_us, pml) templ1 = IntToLong(v19_gabs)*IntToLong(tbw100);\
templ1 = ((templ1*100L)/IntToLong(t_us))*10L;\
templ1 = (templ1*1000L+535L)/1070L;\
templ1 = (templ1*10L+IntToLong(pml)/2L)/IntToLong(pml);\
if ((templ1<1L)||(templ1>IntToLong(crusher_max_dac))||(templ1*100L>IntToLong(crusher_slew_dac_100us)*IntToLong(tramp))) {\
printf("V19 selector DAC %ld outside amplitude/slew ceiling\n", templ1); goto end; }\
dest = templ1*IntToLong(v19_gsign);
// Compensation lobe NEGPULSE_SEC(v19_comp_flat): area -sec*(flat+tramp) exactly
// (library ramps 0_mn_sec/mn_0_sec each 0.5*tramp). Target area after/before the
// RF = -(kappa*T + pad/2 + ramp_area_fraction*tramp) * selector.
#define V19_COMP(dest, g, k10000, t_us, pad_us, ramp10000) templ2 = (IntToLong(k10000)*IntToLong(t_us)+5000L)/10000L + IntToLong(pad_us)/2L + (IntToLong(ramp10000)*IntToLong(tramp)+5000L)/10000L;\
templ1 = IntToLong(g);\
if (templ1<0L) templ1 = -templ1;\
templ1 = (templ1*templ2 + IntToLong(v19_comp_flat+tramp)/2L)/IntToLong(v19_comp_flat+tramp);\
if ((templ1<1L)||(templ1>IntToLong(crusher_max_dac))||(templ1*100L>IntToLong(crusher_slew_dac_100us)*IntToLong(tramp))) {\
printf("V19 compensation DAC %ld outside amplitude/slew ceiling\n", templ1); goto end; }\
dest = templ1*IntToLong(v19_gsign);
#define V19_RFMUL(dest, num) dest = scale(rfcal, num, 10000);\
if ((dest<1)||(dest>2047)) { printf("V19 RF multiplier outside 1..2047\n"); goto end; }
// RF block plateau: RF + 2*rfdelay, rounded up to tramp/10 (v18 crush_rf_flat rule).
#define V19_FLAT(dest, rfn) temp = tramp/10;\
dest = ((rf_length[rfn]+2*rfdelay+temp-1)/temp)*temp;\
if (dest%2!=0) dest = dest+temp;
// RF block window ticks relative to the list start. RF centre = plateau centre
// + rfdelay (the v18-documented gradient group-delay compensation).
// go/off: RF start / gate-off relative to the list start; offl: gate-off
// relative to the pre-RF re-anchor (go-lead). rem: from the post-RF re-anchor
// to list end + 20 us. Every waittimer is issued/targeted < V19_MAX_WAIT.
#define V19_RFTIMES(go, off, offl, rem, blk, pre_us, flat, rfn, list_us) go = (pre_us + v19_r + IntToLong(flat-rf_length[rfn])/2L + v19_rd)*10L;\
off = go + IntToLong(rf_length[rfn])*10L + 50L;\
offl = v19_lead - V19_ANCHOR + IntToLong(rf_length[rfn])*10L + 50L;\
rem = (list_us + 20L)*10L - off - V19_POST_RF - V19_ANCHOR;\
blk = list_us + 20L + V19_TAIL_US;\
if ((go-v19_lead<300L)||(go-v19_lead>V19_MAX_WAIT)||(offl+V19_POST_RF>V19_MAX_WAIT)||(rem<50L)||(rem+V19_TAIL_US*10L>V19_MAX_WAIT)) {\
printf("V19 RF block window infeasible (rf %d)\n", rfn); goto end; }
// Playback of one RF event. Caller has selected matrix/list and set phase.
#define V19_RF_START(mask) starttimer();\
MR3040_Start(mask);\
if (use_pdd>0) userout(pdd_tx_mask);
#define V19_RF_GO(rfn, mul, go, offl) waittimer(go-v19_lead);\
starttimer();\
NEWSHAPE_SETUP(rfn, mul)\
waittimer(v19_unblank);\
rfampon(0);\
if (warmup>10) delay(warmup,us);\
waittimer(v19_lead-V19_ANCHOR);\
rfon(rf_on);\
MR3031_go();\
waittimer(offl);\
rfon(0);\
if (use_pdd>0) userout(pdd_rx_mask);\
waittimer(offl+V19_POST_RF);\
starttimer();
'''

# ---------------------------------------------------------------- setup (once)
SETUP_COMMON_A = r'''
	// [V19-SETUP] Once per scan, before the validator exit and before any event.
	// Method-only PPL: v19_on and the table size were checked at program start.
	v19_mode = 0;
		// Supported-mode gate: unsupported combinations are rejected, never bypassed.
		if ((diff_on!=1)||(crush_independent_on!=1)||(crusher_schedule!=0)||(de_on!=0))
		{ printf("V19 needs DWI ON, independent constant crushers, DE OFF\n"); goto end; }
		if ((flow_comp_on!=0)||(dixon_on!=0)||(no_views_2!=1)||(echoes_to_discard!=0)||(setup_mode!=0))
		{ printf("V19 rejects flow comp, Dixon, 3D, skipped echoes, TREF setup\n"); goto end; }
		if ((no_slices!=1)||(slice_mm_10!=0)||(fov_slice_off[0]!=0))
		{ printf("V19 supports one centred slice (fixed tx frequency for all widths)\n"); goto end; }
		if ((sat_on!=0)||(chess_on!=0)||(mtc_on!=0)||(gating!=0)||(mains_gating!=0)||(TR_array_size!=0))
		{ printf("V19 rejects presat, CHESS, CEST, gating and TR arrays\n"); goto end; }
		if ((gs_on!=1)||(gr_on!=1)||(gsp_lobe!=0)||(post_90_delay1!=0)||(phcor0!=0))
		{ printf("V19 needs slice/read ON, gsp_lobe 0, no post-90/phcor0 trims\n"); goto end; }
		if ((views_per_seg<1)||(views_per_seg>64)||(v19_cycles<1)||(v19_cycles>8))
		{ printf("V19 needs ETL 1..64 and 1..8 dephasing cycles\n"); goto end; }
		if (v19_cycles!=2)
		{ printf("V19 supports only 2 dephasing cycles; re-validate other values with examples/v19_validate_events.py\n"); goto end; }
		if ((diff_tramp!=tramp)||(rfgate_delay<17)||(tramp+rfdelay<163))
		{ printf("V19 needs diff_tramp=tramp, rfgate_delay>=17, tramp+rfdelay>=163 us\n"); goto end; }
		if ((gs_var==0)||(gs_var<-12000)||(gs_var>12000)||(warmup<0)||(warmup>200))
		{ printf("V19 slice selector outside 1..12000 DAC, or warmup outside 0..200 us\n"); goto end; }
		if ((IntToLong(v19_comp_flat)*50L)%IntToLong(tramp)!=0L)
		{ printf("V19 compensation flat must be a multiple of tramp/50\n"); goto end; }
		if (((IntToLong(tdp)*50L)%IntToLong(tramp)!=0L)||(sm_delta_us<=IntToLong(tramp))||(sm_delta_us>32000L)||
		    (((sm_delta_us-IntToLong(tramp))*50L)%IntToLong(tramp)!=0L))
		{ printf("V19 tdp and little delta-tramp must be multiples of tramp/50\n"); goto end; }
		v19_gabs = gs_var;
		v19_gsign = 1;
		if (gs_var<0) { v19_gabs = -gs_var; v19_gsign = -1; }
		v19_r = IntToLong(tramp);
		v19_rd = IntToLong(rfdelay);
		// lead: pre-RF re-anchor -> RF start; the amplifier is unblanked
		// warmup + (rfgate_delay-17) + 10 us before the RF (v18 idiom + 10-us margin).
		v19_lead = IntToLong(warmup+rfgate_delay+60)*10L;
		v19_unblank = v19_lead - IntToLong(warmup+rfgate_delay-17+10)*10L - V19_ANCHOR;
		v19_te_us = IntToLong(te)*1000L;
		v19_esp_us = IntToLong(esp)*1000L;
		v19_tacq_half = tacq/2L;
		v19_nsp = IntToLong(no_samples+no_discard)*IntToLong(sample_period);
		v19_diff_flat = sm_delta_us - v19_r;
		v19_ld = sm_delta_us + v19_r;
		// RF multipliers from the calibrated 90-degree stock-pulse value rfcal.
		V19_RFMUL(v19_mul_ex, 3436)
		V19_RFMUL(v19_mul_rf, 11509)
		v19_i = 0;
v19_flip_check:
		if ((v19_flip_tenths[v19_i]<1)||(v19_flip_tenths[v19_i]>1800))
		{ printf("V19 refocusing flip %d outside 0.1..180 deg\n", v19_i+1); goto end; }
		temp = scale(10783, v19_flip_tenths[v19_i], 1800);
		V19_RFMUL(v19_mul[v19_i], temp)
		v19_i = v19_i+1;
		if (v19_i<views_per_seg) goto v19_flip_check;
		V19_FLAT(v19_f_ex, 18)
		V19_FLAT(v19_f_rf, 19)
		V19_FLAT(v19_f_im, 23)
		// Imaging selector for TBW 1.54 / 1200 us at the protocol slice width.
		V19_SELECTOR(v19_g_im, 154, 1200, 1000)
		// Added dephasing: v19_cycles across the imaging slice defined by gs_var;
		// D_dac = cycles*|gs_var|*1e6/(1070*(tdp+tramp)) (gradient calibration cancels).
		// (1070 Hz band). D lobe = POSPULSE_SEC(tdp): area D*(tdp+tramp*1.0096);
		// recall/restoration use the identical shape in slice_list_rp.
		templ1 = (IntToLong(v19_gabs)*10000L)/107L;
		templ1 = (templ1*IntToLong(v19_cycles)*10L + IntToLong(tdp+tramp)/2L)/IntToLong(tdp+tramp);
		if ((templ1<1L)||(templ1>IntToLong(crusher_max_dac))||(templ1*100L>IntToLong(crusher_slew_dac_100us)*IntToLong(tramp)))
		{ printf("V19 added-dephasing DAC %ld outside ceiling\n", templ1); goto end; }
		// D takes the train-crusher polarity (Gibbons Fig 1: right crusher C+D,
		// left C-D). |C| >= 3|D| keeps C-D, C+D and C+2D away from zero so FIDs
		// and FID-echo pathways of every imaging RF remain spoiled.
		if (crusher_saved_train==0) { printf("V19 needs a nonzero train crusher\n"); goto end; }
		v19_d_dac = templ1;
		if (crusher_saved_train<0) v19_d_dac = -v19_d_dac;
		templ2 = IntToLong(crusher_saved_train)*IntToLong(tcrush+tramp);
		if (templ2<0L) templ2 = -templ2;
		if (templ2<3L*templ1*IntToLong(tdp+tramp))
		{ printf("V19 train crusher area must be >= 3x added dephasing (C=%ld, D=%ld DAC.us)\n", templ2, templ1*IntToLong(tdp+tramp)); goto end; }
		// Imperfect preparation RF creates further C1 coincidence families.
		// Restrict both crushers to the Bloch-validated two-cycle geometry.
		templ3 = IntToLong(crusher_saved_first)*IntToLong(diff_tcrush+tramp);
		if (templ3<0L) templ3 = -templ3;
		templ4 = templ1*IntToLong(tdp+tramp);
		// Ratios C/D=3.83 +/-0.02, C1/D=2.55 +/-0.02. Divide before
		// multiplication to keep the comparisons inside signed 32-bit arithmetic.
		if ((crusher_saved_first>=0)||(crusher_saved_train>=0)||
		    (templ2/100L<(templ4/100L)*381L/100L)||(templ2/100L>(templ4/100L)*385L/100L)||
		    (templ3/100L<(templ4/100L)*253L/100L)||(templ3/100L>(templ4/100L)*257L/100L))
		{ printf("V19 crusher geometry unvalidated; use C/D=3.83 and C1/D=2.55, then re-validate with examples/v19_validate_events.py\n"); goto end; }
'''

SETUP_SSMGOT = r'''
		// ss-MGOT: slab preparation, narrower tip-up, imaging-width re-excitation.
		if ((v19_slab_pml<1000)||(v19_tip_pml<1000)||(v19_tip_pml>v19_slab_pml))
		{ printf("V19 needs imaging <= tip-up <= slab width\n"); goto end; }
		V19_SELECTOR(v19_g_ex, 355, 3200, v19_slab_pml)
		V19_SELECTOR(v19_g_rf, 355, 3200, v19_slab_pml)
		V19_SELECTOR(v19_g_m, 355, 3200, v19_tip_pml)
		V19_SELECTOR(v19_g_re, 154, 1200, 1000)
		V19_FLAT(v19_f_m, 20)
		V19_FLAT(v19_f_re, 22)
		V19_COMP(v19_c_ex, v19_g_ex, 5316, rf_length[18], v19_f_ex-rf_length[18], 5096)
		V19_COMP(v19_c_m, v19_g_m, 5318, rf_length[20], v19_f_m-rf_length[20], 4904)
		V19_COMP(v19_c_re, v19_g_re, 5547, rf_length[22], v19_f_re-rf_length[22], 5096)
		V19_RFMUL(v19_mul_m, 3761)
		V19_RFMUL(v19_mul_re, 5392)
		// Spoiler: v19_spoil_cpmm cycles/mm on the phase axis, POSPULSE area dac*(flat+tramp).
		if ((v19_spoil_dac<1000)||(v19_spoil_dac>crusher_max_dac)||(IntToLong(v19_spoil_dac)*100L>IntToLong(crusher_slew_dac_100us)*IntToLong(tramp))||(grad_varl<1000L))
		{ printf("V19 spoiler amplitude outside ceiling\n"); goto end; }
		templ1 = 32767000L/grad_varl;
		if (IntToLong(v19_spoil_cpmm)*templ1>2000000L)
		{ printf("V19 spoiler moment too large for this gradient\n"); goto end; }
		templ1 = (IntToLong(v19_spoil_cpmm)*templ1*1000L + IntToLong(v19_spoil_dac)-1L)/IntToLong(v19_spoil_dac) - v19_r;
		temp = tramp/50;
		templ1 = ((templ1+IntToLong(temp)-1L)/IntToLong(temp))*IntToLong(temp);
		if ((templ1<IntToLong(tramp))||(templ1>6000L))
		{ printf("V19 spoiler flat %ld us outside tramp..6000 us\n", templ1); goto end; }
		v19_t_sp = templ1;
'''

SETUP_ALSOP = r'''
		// Alsop: slice-selective preparation and elimination at the imaging width.
		V19_SELECTOR(v19_g_ex, 355, 3200, 1000)
		V19_SELECTOR(v19_g_rf, 355, 3200, 1000)
		V19_SELECTOR(v19_g_m, 355, 3200, 1000)
		V19_FLAT(v19_f_m, 21)
		V19_COMP(v19_c_ex, v19_g_ex, 5316, rf_length[18], v19_f_ex-rf_length[18], 5096)
		// Elimination: one symmetric pre/post lobe amplitude; pre ramp-up (0.4904)
		// and post ramp-down (0.5096) areas differ by 0.0192*tramp*selector, which
		// is reported by the event audit rather than hidden.
		V19_COMP(v19_c_m, v19_g_m, 5309, rf_length[21], v19_f_m-rf_length[21], 5000)
		V19_RFMUL(v19_mul_m, 3761)
'''

SETUP_LISTS = {
    "ssmgot": r'''
		// Gradient lists (appended after all v18 lists; v18 addresses unchanged).
		v19_l_ex = MR3040_InitList();
		POSPULSE(v19_f_ex, clock)
		NEGPULSE_SEC(v19_comp_flat, clock)
		v19_l_rf = MR3040_InitList();
		POSPULSE_SEC(diff_tcrush, clock)
		POSPULSE(v19_f_rf, clock)
		POSPULSE_SEC(diff_tcrush, clock)
		v19_l_diff = MR3040_InitList();
		POSPULSE(v19_diff_flat, clock)
		v19_l_d = MR3040_InitList();
		POSPULSE_SEC(tdp, clock)
		v19_l_m = MR3040_InitList();
		NEGPULSE_SEC(v19_comp_flat, clock)
		POSPULSE(v19_f_m, clock)
		v19_l_sp = MR3040_InitList();
		POSPULSE(v19_t_sp, clock)
		v19_l_re = MR3040_InitList();
		POSPULSE(v19_f_re, clock)
		NEGPULSE_SEC(v19_comp_flat, clock)
		v19_mr_zero = v19_f_re+2*tramp;
		v19_l_rr = MR3040_InitList();
		DELAY(v19_mr_zero, clock, "zeros")
		NEGPULSE_SEC(tdp, clock)
		v19_l_im = MR3040_InitList();
		POSPULSE_SEC(tcrush, clock)
		POSPULSE(v19_f_im, clock)
		POSPULSE_SEC(tcrush, clock)
''',
    "alsop": r'''
		// Gradient lists (appended after all v18 lists; v18 addresses unchanged).
		v19_l_ex = MR3040_InitList();
		POSPULSE(v19_f_ex, clock)
		NEGPULSE_SEC(v19_comp_flat, clock)
		v19_l_rf = MR3040_InitList();
		POSPULSE_SEC(diff_tcrush, clock)
		POSPULSE(v19_f_rf, clock)
		POSPULSE_SEC(diff_tcrush, clock)
		v19_l_diff = MR3040_InitList();
		POSPULSE(v19_diff_flat, clock)
		v19_l_d = MR3040_InitList();
		POSPULSE_SEC(tdp, clock)
		v19_l_m = MR3040_InitList();
		NEGPULSE_SEC(v19_comp_flat, clock)
		POSPULSE(v19_f_m, clock)
		NEGPULSE_SEC(v19_comp_flat, clock)
		v19_mr_zero = v19_comp_flat+v19_f_m+4*tramp;
		v19_l_mr = MR3040_InitList();
		DELAY(v19_mr_zero, clock, "zeros")
		NEGPULSE_SEC(tdp, clock)
		v19_l_im = MR3040_InitList();
		POSPULSE_SEC(tcrush, clock)
		POSPULSE(v19_f_im, clock)
		POSPULSE_SEC(tcrush, clock)
''',
}

# Timeline relative to the preparation-excitation RF centre (t=0), in us.
SETUP_TIMING_COMMON = r'''
		// ---- Timeline (us, prep-90 RF centre = 0). List start s, block length b.
		// RF block: list start -> RF centre = pre + tramp + plateau/2 + rfdelay.
		v19_s_ex = -v19_rd - IntToLong(v19_f_ex/2) - v19_r;
		templ3 = IntToLong(v19_f_ex) + 4L*v19_r + IntToLong(v19_comp_flat);
		V19_RFTIMES(v19_go_ex, v19_off_ex, v19_offl_ex, v19_rem_ex, v19_b_ex, 0L, v19_f_ex, 18, templ3)
		templ3 = 2L*IntToLong(diff_tcrush) + IntToLong(v19_f_rf) + 6L*v19_r;
		v19_s_rf = v19_te_us/2L - v19_rd - IntToLong(v19_f_rf/2) - 3L*v19_r - IntToLong(diff_tcrush);
		V19_RFTIMES(v19_go_rf, v19_off_rf, v19_offl_rf, v19_rem_rf, v19_b_rf, IntToLong(diff_tcrush)+2L*v19_r, v19_f_rf, 19, templ3)
		// Diffusion lobes symmetric about the prep-180 plateau centre, Delta onset-to-onset.
		v19_a1 = v19_te_us/2L - v19_rd - (big_delta_us + v19_ld)/2L;
		v19_a2 = v19_a1 + big_delta_us;
		v19_b_df = v19_ld + 20L + V19_TAIL_US;
		v19_df_wait = (v19_ld + 20L)*10L - 1000L - 2L*V19_ANCHOR;
		v19_b_d = IntToLong(tdp) + 2L*v19_r + 20L + V19_TAIL_US;
		v19_read_len = 2L*IntToLong(tdp) + tacq + 6L*v19_r;
		templ3 = 2L*IntToLong(tcrush) + IntToLong(v19_f_im) + 6L*v19_r;
		V19_RFTIMES(v19_go_im, v19_off_im, v19_offl_im, v19_rem_im, v19_b_im, IntToLong(tcrush)+2L*v19_r, v19_f_im, 23, templ3)
'''

SETUP_TIMING_METHOD = {
    "alsop": r'''
		// Elimination centred on the prep echo; S list = pre-comp, selector, post-comp;
		// R list plays the single read prephaser (v18 area G1*(tref+tramp)) after it.
		v19_s_m = v19_te_us - v19_rd - IntToLong(v19_f_m/2) - 3L*v19_r - IntToLong(v19_comp_flat);
		templ3 = 2L*IntToLong(v19_comp_flat) + IntToLong(v19_f_m) + 6L*v19_r;
		templ4 = IntToLong(v19_mr_zero) + IntToLong(tdp) + 2L*v19_r;
		if (templ4>templ3) templ3 = templ4;
		V19_RFTIMES(v19_go_m, v19_off_m, v19_offl_m, v19_rem_m, v19_b_m, IntToLong(v19_comp_flat)+2L*v19_r, v19_f_m, 21, templ3)
		v19_t0 = v19_te_us;
		v19_len = v19_s_m + v19_b_m;
		v19_s_1 = v19_t0 + v19_esp_us/2L - v19_rd - IntToLong(v19_f_im/2) - 3L*v19_r - IntToLong(tcrush);
		v19_first_wait = (v19_s_1 - v19_len)*10L + V19_TAIL_US*10L + v19_rem_m - V19_ANCHOR;
''',
    "ssmgot": r'''
		// Tip-up centred on the prep echo; then spoiler; then re-excitation (T0).
		v19_s_m = v19_te_us - v19_rd - IntToLong(v19_f_m/2) - 3L*v19_r - IntToLong(v19_comp_flat);
		templ3 = IntToLong(v19_comp_flat) + IntToLong(v19_f_m) + 4L*v19_r;
		V19_RFTIMES(v19_go_m, v19_off_m, v19_offl_m, v19_rem_m, v19_b_m, IntToLong(v19_comp_flat)+2L*v19_r, v19_f_m, 20, templ3)
		v19_s_sp = v19_s_m + v19_b_m + V19_GAP_MIN;
		v19_b_sp = IntToLong(v19_t_sp) + 2L*v19_r + 20L + V19_TAIL_US;
		v19_s_re = v19_s_sp + v19_b_sp + V19_GAP_MIN;
		templ3 = IntToLong(v19_f_re) + 4L*v19_r + IntToLong(v19_comp_flat);
		templ4 = IntToLong(v19_mr_zero) + IntToLong(tdp) + 2L*v19_r;
		if (templ4>templ3) templ3 = templ4;
		V19_RFTIMES(v19_go_re, v19_off_re, v19_offl_re, v19_rem_re, v19_b_re, 0L, v19_f_re, 22, templ3)
		v19_t0 = v19_s_re + v19_r + IntToLong(v19_f_re/2) + v19_rd;
		v19_len = v19_s_re + v19_b_re;
		v19_gap_ms = (v19_s_sp - v19_s_m - v19_b_m)*10L - 2L*V19_ANCHOR;
		v19_gap_sr = (v19_s_re - v19_s_sp - v19_b_sp)*10L - 2L*V19_ANCHOR;
		if (v19_b_sp*10L>V19_MAX_WAIT)
		{ printf("V19 spoiler window %ld us exceeds the 4.9-ms timer budget; raise spoiler DAC\n", v19_b_sp); goto end; }
		v19_s_1 = v19_t0 + v19_esp_us/2L - v19_rd - IntToLong(v19_f_im/2) - 3L*v19_r - IntToLong(tcrush);
		v19_first_wait = (v19_s_1 - v19_len)*10L + V19_TAIL_US*10L + v19_rem_re - V19_ANCHOR;
''',
}

SETUP_TIMING_TAIL = r'''
		// D lobe directly precedes the method list; imaging train from T0.
		v19_s_d = v19_s_m - V19_GAP_MIN - v19_b_d;
		v19_e_1 = v19_t0 + v19_esp_us - v19_rd - 3L*v19_r - IntToLong(tdp) - v19_tacq_half;
		// Gaps (ticks) between consecutive block windows. RF/diffusion blocks end
		// V19_ANCHOR after their nominal length because of one re-anchoring.
		v19_gap_x1 = (v19_a1 - v19_s_ex - v19_b_ex)*10L - 2L*V19_ANCHOR;
		v19_gap_1r = (v19_s_rf - v19_a1 - v19_b_df)*10L - 2L*V19_ANCHOR;
		v19_gap_r2 = (v19_a2 - v19_s_rf - v19_b_rf)*10L - 2L*V19_ANCHOR;
		v19_gap_2d = (v19_s_d - v19_a2 - v19_b_df)*10L - 2L*V19_ANCHOR;
		v19_gap_dm = (v19_s_m - v19_s_d - v19_b_d)*10L - 2L*V19_ANCHOR;
		v19_gap_ir = (v19_e_1 - v19_s_1 - v19_b_im)*10L - 2L*V19_ANCHOR;
		// Readout block (relative to read-list start E): ADC initiate at
		// 3*tramp+tdp+rfdelay (v18 pattern); ADC window ends N*sp-3 ticks after the
		// post-initiate anchor; re-anchor 1 ms before complete().
		v19_rd_a1 = (2L*v19_r + IntToLong(tdp))*10L;
		v19_rd_a2 = (3L*v19_r + IntToLong(tdp) + v19_rd)*10L;
		v19_adc_mid = v19_nsp - 3L - V19_ADC_SLOW - 10000L - 4L*V19_ANCHOR;
		// Anchor A2 = E + rd_a2 + initiate + 3000 + adc_mid + 4 transitions (ticks);
		// complete() then falls exactly N*sp-3 ticks after the post-initiate anchor.
		templ1 = v19_rd_a2 + V19_INIT_COST + V19_ADC_SLOW + v19_adc_mid + 4L*V19_ANCHOR;
		v19_post_a = (v19_read_len + 10L)*10L - templ1;
		v19_post_b = (v19_s_1 + v19_esp_us - v19_e_1)*10L - templ1 - V19_ANCHOR;
		v19_post_end = v19_post_a + V19_TAIL_US*10L;
		// Feasibility: every gap, window and ordering requirement; reject, never stretch.
		if ((v19_gap_x1<V19_GAP_MIN*10L)||(v19_gap_1r<V19_GAP_MIN*10L)||(v19_gap_r2<V19_GAP_MIN*10L)||
		    (v19_gap_2d<V19_GAP_MIN*10L)||(v19_gap_dm<V19_GAP_MIN*10L-2L*V19_ANCHOR))
		{ printf("V19 TE/Delta/delta too short for prep (gaps %ld %ld %ld %ld ticks)\n", v19_gap_x1, v19_gap_1r, v19_gap_r2, v19_gap_2d); goto end; }
		if ((v19_s_1-v19_len<V19_GAP_MIN)||(v19_first_wait>V19_MAX_WAIT)||(v19_gap_ir<V19_GAP_MIN*10L))
		{ printf("V19 ESP too short after method block or before readout (%ld %ld)\n", v19_first_wait, v19_gap_ir); goto end; }
		if ((v19_adc_mid<100L)||(v19_first_wait>V19_MAX_WAIT)||(v19_post_a<(10000L+IntToLong(tfilter)*10L+1000L))||(v19_post_b<v19_post_a+V19_TAIL_US*10L+V19_GAP_MIN*10L)||
		    (v19_post_b>V19_MAX_WAIT)||(v19_rd_a2>V19_MAX_WAIT)||(v19_df_wait<1000L))
		{ printf("V19 ESP/ADC too short for readout and restoration (%ld %ld %ld)\n", v19_adc_mid, v19_post_a, v19_post_b); goto end; }
		if ((v19_rd_a1<4000L)||(v19_go_im-v19_lead<2500L)||(v19_b_d*10L>V19_MAX_WAIT)||(v19_post_end>V19_MAX_WAIT))
		{ printf("V19 readout/imaging/D windows outside budget (need 2*tramp+tdp>=400 us)\n"); goto end; }
		if ((v19_e_1-v19_s_1)+v19_read_len+V19_GAP_MIN+V19_TAIL_US>v19_esp_us)
		{ printf("V19 ESP too short for crusher + readout\n"); goto end; }
		// Shot length from the first method statement (100 us before the prep list)
		// to the end of the last read list; TR adds v18 setup windows below.
		v19_shot_us = (v19_e_1 + IntToLong(views_per_seg-1)*v19_esp_us + v19_read_len + 10L + V19_TAIL_US) - (v19_s_ex - 100L);
		v19_mode = 1;   // latched: per-shot branches test v19_mode, not the PARAMLIST switch
		if (report_on==1)
		{
			printf("V19 prep TE=%ld us, first imaging RF centre=%ld us, first echo=%ld us, ESP=%ld us\n", v19_te_us, v19_t0+v19_esp_us/2L, v19_t0+v19_esp_us, v19_esp_us);
			printf("V19 shot %ld us; D=%d DAC; mul ex/rf/m=%d/%d/%d\n", v19_shot_us, v19_d_dac, v19_mul_ex, v19_mul_rf, v19_mul_m);
		}
'''

# ---------------------------------------------------------------- per shot
# ------------------------------------------------------------- method only
# The combined v18+method image exceeded the 64K RTX image (v18 history:
# "too big to fit in 64K"; pplsim "step math opcodes" and corrupted
# parameters). The method PPLs therefore omit what the method path can never
# run; controls use the unchanged v18 PPL.
# v18 regions the method path always jumped over (start, end anchors). The
# kernel region starts at its anchor; the method shot replaces it.
SKIPPED_V18 = [
    ("\tstarttimer();\n\t// TE calculations\n", "\twaittimer(5300);\n", False),
    ("/*  Calculation of te extend time */\n",
     "/*  Calculate phase increment following each 180 degree pulse */", False),
    ("\twaittimer(30000); // 3000 us; included in the 11350-us TR overhead\n",
     "#ifdef POST_ETL_CRUSHER\n\t// 240 us gap", True),
]
KERNEL_JUMP = "\tgoto v19_mat_window;\nv19_after_train:\n"
# Optional v18 features the method gate rejects (E2/E3/E5); commented out in
# v18's own style (\\#define MAINSGATE). Their variables stay declared.
REJECTED_FEATURES = ["MULTIPRESAT", "FSE3D", "DRIVEN_EQUILIBRIUM", "SKIP_FIRST_ECHOES", "CHESS",
                     "AUTOGATE", "MTC", "PRESAT_FREQ_FLIP", "DIXON3P"]
# Table capacities: 64 diffusion rows (the v1.x size before 512) and one
# crusher/multiplier entry per echo (method ETL <= 64, E7; E87 still checks).
MAX_DIFF_ACQ = 64
TABLE_DEFINES = {"#define MAX_DIFF_ACQ 512\n": f"#define MAX_DIFF_ACQ {MAX_DIFF_ACQ}\n",
                 "#define MAX_CRUSHER_ETL 1024\n": "#define MAX_CRUSHER_ETL 64\n"}
EARLY_GUARD = r'''	// [V19] Method-only PPL. Checked before any calculation reads the tables.
	if (v19_on!=1)
	{ printf("V19 method-only PPL: v19_on must be 1\n"); goto end; }
	if ((no_diff_acq<1)||(no_diff_acq>MAX_DIFF_ACQ))
	{ printf("V19 needs 1..64 diffusion acquisitions\n"); goto end; }
'''


def method_only(t):
    """Remove v18 code the method path cannot reach and size tables for it."""
    for start, end, inclusive in SKIPPED_V18:
        assert t.count(start) == 1 and t.count(end) == 1, start
        i = t.index(start) + (0 if inclusive else len(start))
        j = t.index(end)
        assert i < j
        region = t[i:j]
        assert (len(re.findall(r'(?m)^\s*#if', region)) == len(re.findall(r'(?m)^\s*#endif', region)))
        labels = re.findall(r'(?m)^\s*([A-Za-z_]\w*):(?!=)', region)
        rest = t[:i] + t[j:]
        assert not any(re.search(r'\bgoto\s+' + l + r'\s*;', rest) for l in labels), labels
        t = t[:i] + (KERNEL_JUMP if inclusive else '') + t[j:]
    for name in REJECTED_FEATURES:
        pattern = r'(?m)^#define ' + name + r'\b'
        assert len(re.findall(pattern, t)) == 1, name
        t = re.sub(pattern, r'\\\\#define ' + name, t)
    for old, new in TABLE_DEFINES.items():
        assert t.count(old) == 1, old
        t = t.replace(old, new)
    old = '"%d",1,512,1,1,no_diff_acq;'
    assert t.count(old) == 1
    t = t.replace(old, f'"%d",1,{MAX_DIFF_ACQ},1,1,no_diff_acq;')
    for name in ("acq_b", "acq_grad", "acq_x", "acq_y", "acq_z"):
        pattern = r'(VAR_ARRAY [^\n]*,' + name + r', )512;'
        assert len(re.findall(pattern, t)) == 1, name
        t = re.sub(pattern, r'\g<1>' + str(MAX_DIFF_ACQ) + ';', t)
    return t
TR_OVERRIDE = r'''	// [V19-TR] method shot replaces the v18 90->last-echo estimate; the v18
	// code below then applies TR defaults, the TR error exit and the gating
	// bookkeeping unchanged. tr_min = shot + v18 timed setup windows (11350 us)
	// + untimed 70+69 us + two V19 matrix windows (2 x 2500 us) + post crusher.
	if (v19_mode==1)
	{
		tr_min = v19_shot_us + 11350L + 70L + 69L + 5000L;
#ifdef POST_ETL_CRUSHER
		if (post_crush_on)
			tr_min = tr_min + IntToLong(2*tramp+post_tcrush+240);
#endif
	}
'''

MATRICES = {
    "alsop": r'''		// [V19-MATRICES] all method matrices, under ss_mat, before the shot.
		starttimer();
		MR3040_SelectMatrix( ss_mat );
		CREATE_MATRIX(v19_m_ex, gs_on*v19_g_ex, 0, 0)
		delay(caldelay,us);
		CREATE_MATRIX(v19_m_ex+256, gs_on*v19_c_ex, 0, 0)
		delay(caldelay,us);
		CREATE_MATRIX(v19_m_rf, gs_on*v19_g_rf, 0, 0)
		delay(caldelay,us);
		CREATE_MATRIX(v19_m_rf+256, gs_on*crusher_saved_first, 0, 0)
		delay(caldelay,us);
		CREATE_MATRIX(v19_m_d, 0, 0, 0)
		delay(caldelay,us);
		v19_setup_ticks = gettimer();
		if ((v19_setup_ticks<0)||(v19_setup_ticks>20000))
		{ printf("V19 matrix window 1 overrun\n"); goto end; }
		waittimer(25000);
		starttimer();
		CREATE_MATRIX(v19_m_d+256, gs_on*v19_d_dac, 0, 0)
		delay(caldelay,us);
		CREATE_MATRIX(v19_m_m, gs_on*v19_g_m, 0, 0)
		delay(caldelay,us);
		// read prephaser: v18 area G1*(tref+tramp) on a tdp lobe
		templ1 = (IntToLong(G1)*IntToLong(tref+tramp))/IntToLong(tdp+tramp);
		if ((templ1<-IntToLong(crusher_max_dac))||(templ1>IntToLong(crusher_max_dac))||
		    (templ1*100L>IntToLong(crusher_slew_dac_100us)*IntToLong(tramp))||(-templ1*100L>IntToLong(crusher_slew_dac_100us)*IntToLong(tramp)))
		{ printf("V19 read prephaser DAC %ld outside ceiling\n", templ1); goto end; }
		v19_rp_dac = templ1;
		CREATE_MATRIX(v19_m_m+256, gs_on*v19_c_m, 0, gr_on*v19_rp_dac)
		delay(caldelay,us);
		CREATE_MATRIX(v19_m_im, gs_on*v19_g_im, 0, 0)
		delay(caldelay,us);
		CREATE_MATRIX(v19_m_im+256, gs_on*crusher_saved_train, 0, 0)
		delay(caldelay,us);
		v19_setup_ticks = gettimer();
		if ((v19_setup_ticks<0)||(v19_setup_ticks>20000))
		{ printf("V19 matrix window 2 overrun\n"); goto end; }
		waittimer(25000);
''',
    "ssmgot": r'''		// [V19-MATRICES] all method matrices, under ss_mat, before the shot.
		starttimer();
		MR3040_SelectMatrix( ss_mat );
		CREATE_MATRIX(v19_m_ex, gs_on*v19_g_ex, 0, 0)
		delay(caldelay,us);
		CREATE_MATRIX(v19_m_ex+256, gs_on*v19_c_ex, 0, 0)
		delay(caldelay,us);
		CREATE_MATRIX(v19_m_rf, gs_on*v19_g_rf, 0, 0)
		delay(caldelay,us);
		CREATE_MATRIX(v19_m_rf+256, gs_on*crusher_saved_first, 0, 0)
		delay(caldelay,us);
		CREATE_MATRIX(v19_m_d, 0, 0, 0)
		delay(caldelay,us);
		CREATE_MATRIX(v19_m_d+256, gs_on*v19_d_dac, 0, 0)
		delay(caldelay,us);
		CREATE_MATRIX(v19_m_m, gs_on*v19_g_m, 0, 0)
		delay(caldelay,us);
		v19_setup_ticks = gettimer();
		if ((v19_setup_ticks<0)||(v19_setup_ticks>20000))
		{ printf("V19 matrix window 1 overrun\n"); goto end; }
		waittimer(25000);
		starttimer();
		CREATE_MATRIX(v19_m_m+256, gs_on*v19_c_m, 0, 0)
		delay(caldelay,us);
		CREATE_MATRIX(v19_m_sp, 0, v19_spoil_dac, 0)
		delay(caldelay,us);
		CREATE_MATRIX(v19_m_sp+256, 0, 0, 0)
		delay(caldelay,us);
		CREATE_MATRIX(v19_m_re, gs_on*v19_g_re, 0, 0)
		delay(caldelay,us);
		templ1 = (IntToLong(G1)*IntToLong(tref+tramp))/IntToLong(tdp+tramp);
		if ((templ1<-IntToLong(crusher_max_dac))||(templ1>IntToLong(crusher_max_dac))||
		    (templ1*100L>IntToLong(crusher_slew_dac_100us)*IntToLong(tramp))||(-templ1*100L>IntToLong(crusher_slew_dac_100us)*IntToLong(tramp)))
		{ printf("V19 read prephaser DAC %ld outside ceiling\n", templ1); goto end; }
		v19_rp_dac = templ1;
		CREATE_MATRIX(v19_m_re+256, gs_on*v19_c_re, 0, gr_on*v19_rp_dac)
		delay(caldelay,us);
		CREATE_MATRIX(v19_m_im, gs_on*v19_g_im, 0, 0)
		delay(caldelay,us);
		CREATE_MATRIX(v19_m_im+256, gs_on*crusher_saved_train, 0, 0)
		delay(caldelay,us);
		v19_setup_ticks = gettimer();
		if ((v19_setup_ticks<0)||(v19_setup_ticks>20000))
		{ printf("V19 matrix window 2 overrun\n"); goto end; }
		waittimer(25000);
''',
}

MATRIX_DEFS = '''// [V19] method matrices (primary id, secondary id+256); none overlap v18 ids.
#define v19_m_ex 40
#define v19_m_rf 41
#define v19_m_d 42
#define v19_m_m 43
#define v19_m_im 44
#define v19_m_sp 45
#define v19_m_re 46
'''


# ---------------------------------------------------------------- the shot
SHOT_PREP = r'''
	goto end;
// =====================================================================
// [V19-SHOT] Method shot. Every gradient/RF/ADC event is placed by padded
// starttimer/waittimer windows anchored on list starts, or by exact delay32
// gaps between windows. Landmark comments name the simulation snapshots.
// =====================================================================
v19_mat_window:
	waittimer(30000); // the v18 setup window, completed on the method path
	// [V19-MATRICES] all method matrices under ss_mat, before the shot (2 x 2500 us)
@MATRICES@	resync();
	gp_sl_var = 0;     // 3D rejected; v18 assigns this only on its own path
	echo_cnt = 0;
	total_echo_cnt = 0;
	resync();
	starttimer();
		MR3040_Clock(clock);
		MR3040_SelectMatrix(v19_m_ex);
		MR3040_SetList(v19_l_ex, CHANNEL_S);
		phase(phase_90);                         // prep excitation, axis 0 deg
	waittimer(1000);
	// [V19-EX] preparation excitation (slab-selective for ss-MGOT)
	V19_RF_START(CHANNEL_S)
	V19_RF_GO(18, v19_mul_ex, v19_go_ex, v19_offl_ex)
	waittimer(v19_rem_ex);
		MR3040_SelectMatrix(diff_mat);
		MR3040_SetList(v19_l_diff, ALL_CHANNELS);
	waittimer(v19_rem_ex+V19_TAIL_US*10L);
	delay32(v19_gap_x1);
	// [V19-DIFF1] first diffusion lobe
	starttimer();
		MR3040_Start(ALL_CHANNELS);
	waittimer(1000);
	delay32(v19_df_wait);
	starttimer();
		MR3040_SelectMatrix(v19_m_rf);
		MR3040_SetList(v19_l_rf, CHANNEL_S);
		phase(phase_180);                        // prep refocus, axis 270 deg
	waittimer(V19_TAIL_US*10L);
	delay32(v19_gap_1r);
	// [V19-RF180] preparation refocusing, first-diffusion crushers
	V19_RF_START(CHANNEL_S)
	V19_RF_GO(19, v19_mul_rf, v19_go_rf, v19_offl_rf)
	waittimer(v19_rem_rf);
		MR3040_SelectMatrix(diff_mat);
		MR3040_SetList(v19_l_diff, ALL_CHANNELS);
	waittimer(v19_rem_rf+V19_TAIL_US*10L);
	delay32(v19_gap_r2);
	// [V19-DIFF2] second diffusion lobe
	starttimer();
		MR3040_Start(ALL_CHANNELS);
	waittimer(1000);
	delay32(v19_df_wait);
	starttimer();
		MR3040_SelectMatrix(v19_m_d);
		MR3040_SetList(v19_l_d, CHANNEL_S);
	waittimer(V19_TAIL_US*10L);
	delay32(v19_gap_2d);
	// [V19-A] landmark A: before added dephasing
	// [V19-D] added dephasing lobe (+D on slice axis); landmark B at its end
	starttimer();
		MR3040_Start(CHANNEL_S);
	waittimer((v19_b_d-V19_TAIL_US)*10L);
'''

SHOT_METHOD = {
    "alsop": r'''		MR3040_SelectMatrix(v19_m_m);
		MR3040_SetList(v19_l_m, CHANNEL_S);
		MR3040_SetList(v19_l_mr, CHANNEL_R);
		phase(phase_180);                        // elimination on refocus axis 270 deg
	waittimer(v19_b_d*10L);
	delay32(v19_gap_dm);
	// [V19-ELIM] selective 90: My retained, Mx -> -Mz; read prephaser on R
	V19_RF_START(CHANNEL_S|CHANNEL_R)
	V19_RF_GO(21, v19_mul_m, v19_go_m, v19_offl_m)
	waittimer(v19_rem_m);
		MR3040_SelectMatrix(v19_m_im);
		MR3040_SetList(v19_l_im, CHANNEL_S);
		phase(phase_180);                        // imaging refocus 270 deg
	// [V19-ENDPOINT] preparation endpoint = imaging-crusher list start
	v19_wait_next = v19_first_wait;
	goto v19_echo_loop;
''',
    "ssmgot": r'''		MR3040_SelectMatrix(v19_m_m);
		MR3040_SetList(v19_l_m, CHANNEL_S);
		phase(phase_90+2*deg_90);                // tip-up axis 180 deg: My -> Mz
	waittimer(v19_b_d*10L);
	delay32(v19_gap_dm);
	// [V19-TIP] selective tip-up (pre-compensated), MG stored on Mz
	V19_RF_START(CHANNEL_S)
	V19_RF_GO(20, v19_mul_m, v19_go_m, v19_offl_m)
	waittimer(v19_rem_m);
		MR3040_SelectMatrix(v19_m_sp);
		MR3040_SetList(v19_l_sp, CHANNEL_P);
	waittimer(v19_rem_m+V19_TAIL_US*10L);
	delay32(v19_gap_ms);
	// [V19-SPOIL] transverse spoiler on the phase axis while MG is longitudinal
	starttimer();
		MR3040_Start(CHANNEL_P);
	waittimer((v19_b_sp-V19_TAIL_US)*10L);
		MR3040_SelectMatrix(v19_m_re);
		MR3040_SetList(v19_l_re, CHANNEL_S);
		MR3040_SetList(v19_l_rr, CHANNEL_R);
		phase(phase_90);                         // re-excitation axis 0 deg
	waittimer(v19_b_sp*10L);
	delay32(v19_gap_sr);
	// [V19-REEXC] slice-selective re-excitation + compensation; read prephaser on R
	V19_RF_START(CHANNEL_S|CHANNEL_R)
	V19_RF_GO(22, v19_mul_re, v19_go_re, v19_offl_re)
	waittimer(v19_rem_re);
		MR3040_SelectMatrix(v19_m_im);
		MR3040_SetList(v19_l_im, CHANNEL_S);
		phase(phase_180);                        // imaging refocus 270 deg
	// [V19-ENDPOINT] preparation endpoint = imaging-crusher list start
	v19_wait_next = v19_first_wait;
	goto v19_echo_loop;
''',
}

SHOT_TRAIN = r'''
// ---- Imaging echo train. The loop top waittimer absorbs the branch cost.
v19_echo_loop:
	waittimer(v19_wait_next);
	// [V19-IMRF] imaging refocusing pulse echo_cnt+1, crushers C/C
	V19_RF_START(CHANNEL_S)
		gp_mul = get_gp_order(current_view+echo_cnt);
		gp_var = (-gp_inc*gp_mul)*nav_cnt;
		// pre-ADC slice-PE lobe carries +D recall (identical shape to the D lobe)
		CREATE_MATRIX(aq_mat_sec,gs_on*(gsp_rp-(gp_sl_var*gp_sl_on*nav_cnt)+v19_d_dac), gp_on*gp_var, gr_on*gr_dp)
	V19_RF_GO(23, v19_mul[echo_cnt], v19_go_im, v19_offl_im)
	waittimer(v19_rem_im);
		MR3040_SelectMatrix( aq_mat );
		MR3040_SetList( read_list, CHANNEL_R );
		MR3040_SetList( phase_list, CHANNEL_P );
		MR3040_SetList( slice_list_rp, CHANNEL_S );
	waittimer(v19_rem_im+V19_TAIL_US*10L);
	delay32(v19_gap_ir);
	// [V19-READ] readout block: identical structure to v18 (ADC at 3*tramp+tdp+rfdelay)
	starttimer();
		MR3040_Start( ALL_CHANNELS );
		CREATE_MATRIX(aq_mat,gs_on*gs_var_rescale,gp_on*gp_var,(gr_on*gr_undersample)*(gr_var/gr_oversample))
		templ1 = IntToLong(fov_phase_deg)*IntToLong(gp_mul);
		templ1 = templ1 + IntToLong(get_gp_var_mul2(current_view_2))*IntToLong(fov_sl_phase_deg);
		phase_rec = templ1%deg_360;
		phase_rec = phase_rec*nav_cnt;
		if (gp_on == 0 ) phase_rec = 0;
		rphase(phase_rec+phase_correction);
		echo_cnt = echo_cnt+1;
		notDummy = -(disacq_cnt >= no_disacq);
		Dummy_Cycles(!notDummy);
	waittimer(v19_rd_a1);
		resync();
		frequency_buffer(1);                    /*  buffer 1 = rx freq */
		reset_frequency();
	waittimer(v19_rd_a2);
	initiate(sample_period);
	starttimer();
		// post-ADC slice-PE lobe carries -D restoration
		CREATE_MATRIX(aq_mat_sec,gs_on*(gsp_rp+(gp_sl_var*gp_sl_on*nav_cnt)-v19_d_dac), gp_on*gp_var, gr_on*gr_dp)
		templ1 = phase_ang;
		total_echo_cnt = total_echo_cnt+1;
		templ2 = IntToLong(total_echo_cnt);
		templ3 = templ1*templ2;
		phase_correction_0 = templ3%IntToLong(deg_360);
		templ5 = templ2*IntToLong(remainder_phase);
		templ4 = templ5/1000L;
		phase_correction_1 = templ4;
		templ4 = templ5%1000L;
		phase_correction_2 = 0;
		if (templ4 > 500 )
			phase_correction_2 = 1;
		if (templ4 < -500 )
			phase_correction_2 = -1;
		phase_correction = (phase_correction_0 + phase_correction_1 + phase_correction_2)%deg_360;
	waittimer(V19_ADC_SLOW);
	delay32(v19_adc_mid);
	starttimer();
	delay32(10000L);
	complete();
		frequency_buffer(0);                    /*  buffer 0 = tx freq */
		reset_frequency();
		phase(phase_180+phase_correction);
	waittimer(v19_post_a);
	// read/phase/slice-PE lists (incl. -D restoration) have finished here
	if (echo_cnt < views_per_seg)
	{
		MR3040_SelectMatrix(v19_m_im);
		MR3040_SetList(v19_l_im, CHANNEL_S);
		v19_wait_next = v19_post_b;
		goto v19_echo_loop;
	}
	waittimer(v19_post_end);
	goto v19_after_train;
'''


def _without_comments(text):
    # Only applied to our additions, never to the inherited v18 source.
    # The console cpp expands identifiers inside // comments. PARAMLIST is a
    # vendor block-comment format, so do not run this on the whole PPL either.
    pattern = r'"(?:[^"\\]|\\.)*"|/\*[\s\S]*?\*/|//[^\n]*'
    return re.sub(pattern, lambda m: m[0] if m[0].startswith('"') else
                  '\n' * m[0].count('\n'), text)


def _arguments(text):
    parts, start, depth = [], 0, 0
    for m in re.finditer(r'"(?:[^"\\]|\\.)*"|[(),\[\]]', text):
        token = m[0]
        if token in ('(', '['):
            depth += 1
        elif token in (')', ']'):
            depth -= 1
        elif token == ',' and depth == 0:
            parts.append(text[start:m.start()].strip())
            start = m.end()
    parts.append(text[start:].strip())
    return parts


def _call_end(text, opening):
    depth = 1
    for m in re.finditer(r'"(?:[^"\\]|\\.)*"|[()]', text[opening + 1:]):
        if m[0] == '(':
            depth += 1
        elif m[0] == ')':
            depth -= 1
        if depth == 0:
            return opening + 1 + m.end()
    raise ValueError('Unclosed generated call')


def _helper_definitions():
    # Expand our helper bodies here, rather than in the console's limited cpp
    # argument buffer. Vendor macros remain in their original supported form.
    logical = re.sub(r'\\\n', '\n', _without_comments(MACROS))
    definitions = {}
    for m in re.finditer(r'^#define (V19_\w+)\(([^)]*)\) ([\s\S]*?)(?=^#define |\Z)',
                         logical, re.M):
        definitions[m[1]] = ([p.strip() for p in m[2].split(',')], m[3].rstrip())
    return definitions


PRINTF_LITERAL_LIMIT = 48  # conservative source-character bound, not a vendor specification


def _short_prints(text):
    pattern = r'\bprintf\s*\('
    start = 0
    while (m := re.search(pattern, text[start:])) is not None:
        begin = start + m.start()
        opening = start + m.end() - 1
        end = _call_end(text, opening)
        args = _arguments(text[opening + 1:end - 1])
        literal = args[0]
        assert literal.startswith('"') and literal.endswith('"'), literal
        body = literal[1:-1]
        if len(body) <= PRINTF_LITERAL_LIMIT:
            start = end
            continue
        # Never split an escape or a conversion. Preserve every character and
        # keep each conversion with its own argument; no added runtime newline.
        atoms = re.findall(r'\\.|%(?:[-+ #0]*\d*(?:\.\d+)?[hlL]?[diuoxXfFeEgGcs]|%)|[^\\%]', body)
        assert ''.join(atoms) == body, body
        chunks, current = [], ''
        for atom in atoms:
            if len(current) + len(atom) > PRINTF_LITERAL_LIMIT:
                chunks.append(current)
                current = ''
            current += atom
        if current:
            chunks.append(current)
        calls, index = [], 1
        for chunk in chunks:
            conversions = re.findall(r'%(?:[-+ #0]*\d*(?:\.\d+)?[hlL]?[diuoxXfFeEgGcs]|%)', chunk)
            count = sum(c != '%%' for c in conversions)
            values = args[index:index + count]
            assert len(values) == count
            index += count
            calls.append('printf("' + chunk + '"' + (', ' + ', '.join(values) if values else '') + ')')
        assert index == len(args), (body, args)
        replacement = ';\n'.join(calls)
        text = text[:begin] + replacement + text[end:]
        start = begin + len(replacement)
    return text


ERROR_MESSAGES = {}


def compact_stopping_diagnostics(text):
    """Replace only terminating diagnostic calls, retaining their goto/guards.

    Comments are masked with equal-length spaces so inherited comment examples
    and parameter definitions are never rewritten.
    """
    lexical = r'"(?:[^"\\]|\\[\s\S])*"|/\*[\s\S]*?\*/|//[^\n]*|\\\\[^\n]*'
    masked = re.sub(lexical, lambda m: m[0] if m[0].startswith('"') else
                    ''.join('\n' if c == '\n' else ' ' for c in m[0]), text)
    changes = []
    for match in re.finditer(r'\bprintf\s*\(', masked):
        end = _call_end(text, match.end() - 1)
        if not re.match(r'\s*;\s*goto end\s*;', masked[end:]):
            continue
        args = _arguments(text[match.end():end - 1])
        if args[0].startswith('"Duration='):
            continue
        key = tuple(args)
        if key not in ERROR_MESSAGES:
            ERROR_MESSAGES[key] = len(ERROR_MESSAGES) + 1
        changes.append((match.start(), end, f'v19_error_code={ERROR_MESSAGES[key]}'))
    for begin, end, replacement in reversed(changes):
        text = text[:begin] + replacement + text[end:]
    return text


def compact_v19_errors(text):
    """Share failure reporting; successful paths retain every guard and value."""
    start = 0
    while (match := re.search(r'\bprintf\s*\(', text[start:])) is not None:
        begin = start + match.start()
        opening = start + match.end() - 1
        end = _call_end(text, opening)
        args = _arguments(text[opening + 1:end - 1])
        following = re.match(r'\s*;\s*goto end\s*;', text[end:])
        if following and args[0].startswith('"V19'):
            key = tuple(args)
            if key not in ERROR_MESSAGES:
                ERROR_MESSAGES[key] = len(ERROR_MESSAGES) + 1
            replacement = f'v19_error_code={ERROR_MESSAGES[key]}; goto v19_fail;'
            text = text[:begin] + replacement + text[end + following.end():]
            start = begin + len(replacement)
        else:
            start = end
    return text


def compiler_compatible(insertion):
    text = _without_comments(insertion)
    # No large function-like V19 definitions are emitted to the scanner.
    if insertion == MACROS + MATRIX_DEFS:
        text = _without_comments(MACROS)
        text = re.sub(r'\\\n', '\n', text)
        text = re.sub(r'^#define V19_\w+\([^)]*\) [\s\S]*?(?=^#define |\Z)', '', text, flags=re.M)
        text += _without_comments(MATRIX_DEFS)
    helpers = _helper_definitions()
    pattern = r'\b(' + '|'.join(helpers) + r')\s*\('
    while (m := re.search(pattern, text)) is not None:
        opening = m.end() - 1
        end = _call_end(text, opening)
        values = _arguments(text[opening + 1:end - 1])
        names, body = helpers[m[1]]
        assert len(names) == len(values), m[1]
        replacements = dict(zip(names, values))
        expanded = re.sub(r'"(?:[^"\\]|\\.)*"|\b[A-Za-z_]\w*\b',
                          lambda token: replacements.get(token[0], token[0]), body)
        text = text[:m.start()] + expanded + text[end:]
    if insertion.startswith(SETUP_COMMON_A):
        text = reduce_setup_conversions(text)
    return _short_prints(compact_v19_errors(text))


def reduce_setup_conversions(text):
    """Remove conversion calls only in untimed setup, preserving expression width.

    Every replacement first evaluates the parenthesized argument as signed int,
    then promotes that result with a long zero. No neighboring expression is
    used to infer promotion, so precedence and left-associative sums are safe.
    """
    long_names = {'templ1', 'templ2', 'templ3', 'templ4', 'templ5', 'tr_min',
                  'sm_delta_us', 'big_delta_us', 'tacq', 'tacq_2'}
    int_names = {'tramp', 'rfdelay', 'warmup', 'rfgate_delay', 'te', 'esp',
                 'no_samples', 'no_discard', 'sample_period', 'crusher_max_dac',
                 'crusher_saved_train', 'crusher_saved_first',
                 'crusher_slew_dac_100us', 'tdp', 'tcrush', 'diff_tcrush',
                 'rf_length', 'temp', 'tfilter', 'views_per_seg'}
    for typ, declaration in re.findall(r'\b(int|long) ([^;]+);', DECL_COMMON + DECL_SSMGOT):
        names = {re.match(r'\w+', v.strip())[0] for v in declaration.split(',')}
        (long_names if typ == 'long' else int_names).update(names)
    for match in reversed(list(re.finditer(r'\bIntToLong\(', text))):
        end = _call_end(text, match.end() - 1)
        argument = text[match.end():end - 1]
        # These setup arguments contain only int names, in-range constants and
        # ordinary arithmetic/indexing. Refuse an unknown or long expression.
        words = set(re.findall(r'[A-Za-z_]\w*', argument))
        literals = re.findall(r'\b\d+\b', argument)
        if (not words <= int_names or
                any(int(n) > 32767 for n in literals) or
                not re.fullmatch(r'[\w\s+*/%()\[\]-]+', argument)):
            raise ValueError('unverified int conversion argument: ' + argument)
        assignment = re.search(r'\b(' + '|'.join(sorted(long_names)) + r')\s*=\s*$', text[:match.start()])
        if argument.isdigit():
            replacement = argument + 'L'
        elif assignment and re.match(r'\s*;', text[end:]):
            replacement = '(' + argument + ')'
        else:
            replacement = '(0L+(' + argument + '))'
        text = text[:match.start()] + replacement + text[end:]
    return text


STOP_HUB_ANCHOR = '\tv19_error_code=0;\n'
STOP_HUB = '\tgoto v19_run;\nv19_fail:\nend:\n\tgoto v19_exit;\nv19_run:\n'
EXIT_LABELS = '\nv19_fail:\nend:\n'


def backward_stop_hub(text):
    """Define the terminating labels before any jump to them.

    PPLC E106 (far scratch space overflow) was raised at the 147th forward
    goto in every failing v19 build, whatever the string, token or conversion
    counts; v18 compiles with 145. Unresolved forward label references are the
    exhausted resource. `end`/`v19_fail` now label a hub after the first
    statement, so every later jump to them, including those expanded from
    vendor macros and includes, resolves immediately. The hub's one forward
    jump reaches the unchanged shared exit at the old label position.
    """
    assert text.count(STOP_HUB_ANCHOR) == 1 and text.count(EXIT_LABELS) == 1
    assert not re.search(r'\bv19_(run|exit)\b', text)
    text = text.replace(EXIT_LABELS, '\nv19_exit:\n')
    hub = text.index(STOP_HUB_ANCHOR) + len(STOP_HUB_ANCHOR)
    assert not re.search(r'\bgoto\b', _without_comments(text[:hub]))
    return text[:hub] + STOP_HUB + text[hub:]


TIMER_SETUP_ANCHOR = '\t\tv19_mode = 1;'
TIMER_DECL_ANCHOR = '\tint v19_error_code;\n'
TIMER_NAMES = (('V19_TAIL_US', 'tail'), ('V19_POST_RF', 'post'), ('V19_ANCHOR', 'anc'),
               ('v19_', ''), ('10L', '10'), ('*', '_x'), ('-', '_m_'), ('+', '_p_'),
               ('(', ''), (')', ''))


def int_timer_arguments(text):
    """Pass int waittimer arguments in the method shot.

    waittimer(int) receives the low 16 bits of a long argument and PPLC emits
    W008 for every such call; with v18's 11 inherited W007/W008 the method shot
    exceeded the 20-message abort limit. Each long argument is assigned to an
    int once setup has validated it (assignment truncates to the same low 16
    bits without a warning); constant arguments become int literals. Arguments
    are evaluated before the wait, so event times are unchanged and the timed
    windows only gain slack.
    """
    longs = set()
    for declaration in re.findall(r'\blong ([^;]+);', DECL_COMMON + DECL_SSMGOT):
        longs.update(re.match(r'\w+', v.strip())[0] for v in declaration.split(','))
    # The only timer argument changed inside the train becomes an int itself.
    longs.discard('v19_wait_next')
    consts = {k: int(v) for k, v in re.findall(r'^#define (V19_\w+) (\d+)L$', MACROS, re.M)}
    begin, end = text.index('\nv19_mat_window:\n'), text.index('\nv19_exit:\n')
    shot = text[begin:end]
    names = {}

    def int_argument(arg):
        words = set(re.findall(r'\b[A-Za-z_]\w*', arg))
        if not words & longs:
            if not words & set(consts) and not re.search(r'\d+L\b', arg):
                return arg
            value = re.sub(r'\bV19_\w+\b', lambda w: str(consts[w[0]]), arg)
            assert re.fullmatch(r'[\dL\s+*()-]+', value), arg
            value = eval(value.replace('L', ''))
            assert 0 <= value <= 32767, arg
            return str(value)
        assert words <= longs | set(consts), arg
        key = arg.replace(' ', '')
        if key not in names:
            name = key
            for old, new in TIMER_NAMES:
                name = name.replace(old, new)
            name = 'v19_i_' + re.sub('_+', '_', name).strip('_')
            assert len(name) <= 31 and not re.search(r'\b' + name + r'\b', text, re.I), name
            names[key] = name
        return names[key]

    out, pos = [], 0
    for m in re.finditer(r'\bwaittimer\(', shot):
        close = _call_end(shot, m.end() - 1)
        out.append(shot[pos:m.end()] + int_argument(shot[m.end():close - 1]) + ')')
        pos = close
    shot = ''.join(out) + shot[pos:]
    shot = re.sub(r'\bv19_wait_next = ([^;]+);',
                  lambda m: 'v19_wait_next = ' + int_argument(m[1].strip()) + ';', shot)
    text = text[:begin] + shot + text[end:]
    setup = text.index(TIMER_SETUP_ANCHOR)
    for key in names:
        for word in set(re.findall(r'v19_\w+', key)):
            later = [m.start() for m in re.finditer(r'\b' + word + r'\s*=(?!=)', text)]
            assert later and max(later) < setup, word
    text = re.sub(r'(\blong [^;]*?)\bv19_wait_next, ', r'\1', text, count=1)
    ints = ['v19_wait_next'] + list(names.values())
    decl = ''.join('\tint ' + ', '.join(ints[i:i + 6]) + ';\n' for i in range(0, len(ints), 6))
    assert text.count(TIMER_DECL_ANCHOR) == 1 and text.count(TIMER_SETUP_ANCHOR) == 1
    text = text.replace(TIMER_DECL_ANCHOR, TIMER_DECL_ANCHOR + decl)
    assign = ''.join(f'\t\t{name} = {key};\n' for key, name in names.items())
    return text.replace(TIMER_SETUP_ANCHOR, assign + TIMER_SETUP_ANCHOR)


def anchor_insert(text, anchor, insertion, *, before=False, occurrence=None):
    count = text.count(anchor)
    if count != 1 and occurrence is None:
        raise SystemExit(f"anchor not unique ({count}): {anchor!r}")
    idx = text.find(anchor) if occurrence is None else [i for i in range(len(text)) if text.startswith(anchor, i)][occurrence]
    pos = idx if before else idx + len(anchor)
    return text[:pos] + compiler_compatible(insertion) + text[pos:]


def build(method):
    ERROR_MESSAGES.clear()
    src = V18.read_bytes()
    assert hashlib.sha256(src).hexdigest() == V18_SHA, "v18 source changed"
    t = src.decode("latin-1").replace("\r\n", "\n")
    assert "\r" not in t
    t = anchor_insert(t, '#use RF1 "c:\\smis\\seqlib\\19lobsinb.seq" pf17\n', USE_LINE)
    params = PARAMS_COMMON + (PARAMS_SSMGOT if method == "ssmgot" else "")
    t = anchor_insert(t, 'DSP_ROUTINE "c:\\smis\\dspe8";', params, before=True)
    t = anchor_insert(t, '#include "m3031_15.pph"\n', MACROS + MATRIX_DEFS)
    t = anchor_insert(t, '#include "m3031_15.pph"\n', "#define v19_mul crusher_dac\n")
    decl = DECL_COMMON + (DECL_SSMGOT if method == "ssmgot" else "")
    t = anchor_insert(t, "\tcommon int fse_gs_comp;\n", decl)
    t = anchor_insert(t, '\tNEWSHAPE_MAC(17, pf15,"gauss" , 20000, 10) // duration and bandwidth are nominal and this pulse should always be not slice selective!!\n', NEWSHAPE)
    setup = (SETUP_COMMON_A + (SETUP_SSMGOT if method == "ssmgot" else SETUP_ALSOP) + SETUP_LISTS[method]
             + SETUP_TIMING_COMMON + SETUP_TIMING_METHOD[method] + SETUP_TIMING_TAIL)
    t = anchor_insert(t, "\tCREATE_MATRIX(ss_mat,0,0,0)\n\tdelay(caldelay,us);\t\t/*  Create a zero matrix", setup, before=True)
    t = anchor_insert(t, "\ttempl1 = IntToLong(no_PB*sat_on)*templ1;\n\ttr_min = tr_min + templ1;\n", TR_OVERRIDE)
    shot = SHOT_PREP.replace("@MATRICES@", MATRICES[method]) + SHOT_METHOD[method] + SHOT_TRAIN
    t = anchor_insert(t, "#ifdef MAINSGATE\n\tprintf(\"Count=%d\\n\", bad_cnt);\n#endif\n", shot)
    t = method_only(t)
    # Legacy cpp/PPLC diagnoses positive 32768 before applying unary minus.
    # Use an in-range constant expression for the same signed minimum value.
    t = re.sub(r'==-32768(?![\w])', '==(-32767-1)', t)
    t = anchor_insert(t, '#ifdef MAINSGATE\n\tbad_cnt = 0;\n#endif\n',
                      '\tv19_error_code=0;\n', before=True)
    t = anchor_insert(t, '#ifdef MAINSGATE\n\tbad_cnt = 0;\n#endif\n', EARLY_GUARD, before=True)
    t = compact_stopping_diagnostics(t)
    # Normal completion and all existing end jumps retain their original label.
    # The shared print runs only after a terminating guard records an error.
    assert t.count('\nend:\n') == 1
    t = t.replace('\nend:\n', '\nv19_fail:\nend:\n\tif (v19_error_code!=0)\n\t\tprintf("V19 error E%d\\n", v19_error_code);\n')
    t = backward_stop_hub(t)
    t = int_timer_arguments(t)
    return t.replace("\n", "\r\n")


def main():
    kappa_check()
    out = {}
    for method, path in OUT.items():
        text = build(method)
        path.write_bytes(text.encode("latin-1"))
        out[path.name] = hashlib.sha256(path.read_bytes()).hexdigest()
        table = {f'E{code}': {'message': args[0][1:-1], 'original_arguments': list(args[1:])}
                 for args, code in ERROR_MESSAGES.items()}
        error_path = ROOT / f'docs/v19/compiler_compatibility/{method}_error_codes.json'
        error_path.write_text(json.dumps(table, indent=2) + '\n', encoding='utf-8')
    write_error_code_text()
    print(json.dumps(out, indent=1))


def write_error_code_text():
    """Console lookup table for the compact "V19 error E<n>" messages."""
    lines = ["Method-only PPLs (no v18 control path; run controls with the v18 PPL and PPR).",
             "Use the PPRs shipped with these PPLs: their diffusion tables hold 64 rows.",
             "Fatal messages print V19 error E<number>; find the code under the correct version below.",
             "Numeric values formerly embedded in fatal messages are omitted ([value]).",
             "Successful validator Duration reporting is unchanged.", ""]
    for method, label in (("ssmgot", "v191 / 1.91"), ("alsop", "v192 / 1.92")):
        table = json.loads((ROOT / f'docs/v19/compiler_compatibility/{method}_error_codes.json').read_text())
        lines.append(label)
        for code, entry in table.items():
            message = re.sub(r'%l?[du]', '[value]', entry['message']).replace('\\n', '').strip()
            lines.append(f"{code}: {message}")
        lines.append("")
    (ROOT / 'docs/v19/compiler_compatibility/v19_error_codes.txt').write_text("\n".join(lines), encoding='utf-8')


# ---------------------------------------------------------------- protocols
CONTROL_PPR = ROOT / "experiments/FSE-DWI_10-05-2026_v18_test1e/FSE-DWI_10-05-2026_v18_test1.ppr"
# Disclosed approximations (docs/v19/README.md): Alsop 1997 p530 first five
# angles completed at 60 deg. Gibbons' Busse schedule is unpublished; with the
# centric eight-echo control (k-space centre at echo 1) the ss-MGOT adaptation
# uses the same stabilised ramp (minimum 60 >= the published 55 deg minimum) so
# the two adaptations differ only in their preparation mechanism.
# Train crusher: 3x the test1e value (-8223 DAC) because the PPL requires
# |C| >= 3|D| (Bloch-event audit: |C|~|D| leaves RF FIDs unspoiled).
METHOD_CRUSH_AMP = -8223
FLIPS = {
    "alsop": [1422, 949, 692, 630, 602, 600, 600, 600],
    "ssmgot": [1422, 949, 692, 630, 602, 600, 600, 600],
}


def ppr_array(name, values, n=64):
    vals = list(values) + [values[-1]] * (n - len(values))
    out = f":VAR_ARRAY {name}, {n}, {vals[0]}\r\n"
    rest = vals[1:]
    for i in range(0, len(rest), 8):
        out += ", " + ", ".join(str(v) for v in rest[i:i + 8]) + "\r\n"
    return out


def build_ppr(method, ppl_name, flips=None):
    text = CONTROL_PPR.read_bytes().decode("latin-1")
    lines = text.split("\r\n")
    assert lines[0].startswith(":PPL ")
    lines[0] = f":PPL {ppl_name}"
    text = "\r\n".join(lines)
    assert text.count(":VAR crush_amp, -2741\r\n") == 1
    text = text.replace(":VAR crush_amp, -2741\r\n", f":VAR crush_amp, {METHOD_CRUSH_AMP}\r\n")
    v = ":VAR v19_on, 1\r\n:VAR v19_cycles, 2\r\n:VAR v19_comp_flat, 1000\r\n"
    v += ppr_array("v19_flip_tenths", flips or FLIPS[method])
    if method == "ssmgot":
        v += (":VAR v19_slab_pml, 3000\r\n:VAR v19_tip_pml, 1667\r\n"
              ":VAR v19_spoil_cpmm, 32\r\n:VAR v19_spoil_dac, 16384\r\n")
    anchor = ":DSP_ROUTINE"
    assert text.count(anchor) == 1
    text = text.replace(anchor, v + anchor)
    # Method-only tables hold MAX_DIFF_ACQ rows; entries beyond no_diff_acq are unused.
    assert int(re.search(r":VAR no_diff_acq, (\d+)\r\n", text).group(1)) <= MAX_DIFF_ACQ
    for name in ("acq_b", "acq_grad", "acq_x", "acq_y", "acq_z"):
        m = re.search(r":VAR_ARRAY " + name + r", 512, ([^\r]*)\r\n((?:,[^\r]*\r\n)*)", text)
        values = [int(x) for x in (m.group(1) + m.group(2)).replace("\r\n", "").split(",") if x.strip()]
        assert len(values) == 512, name
        text = text[:m.start()] + ppr_array(name, values[:MAX_DIFF_ACQ], MAX_DIFF_ACQ) + text[m.end():]
    return text


def main_ppr():
    hashes = {}
    for method, path in OUT.items():
        ppr = path.with_suffix(".ppr")
        ppr.write_bytes(build_ppr(method, path.name).encode("latin-1"))
        hashes[ppr.name] = hashlib.sha256(ppr.read_bytes()).hexdigest()
    print(json.dumps(hashes, indent=1))


if __name__ == "__main__":
    main()
    main_ppr()
