"""Reproduce the additive v1.81 candidate from the immutable v1.8 source.

No existing source or protocol is modified. The default protocol is the acquired
October 5 test1e ETL8/TE54/ESP14 control. Source mapping is not scanner validation.
"""
from __future__ import annotations

import hashlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BASE = ROOT / "scanner/FSE_dwi_CPMG_non_CPMG_twoTE-1.8.ppl"
BASE_PPR = ROOT / "experiments/FSE-DWI_10-05-2026_v18_test1e/FSE-DWI_10-05-2026_v18_test1.ppr"
PPL = ROOT / "scanner/FSE_dwi_CPMG_non_CPMG_twoTE-1.81.ppl"
PPR = ROOT / "scanner/FSE_dwi_CPMG_non_CPMG_twoTE-1.81.ppr"
BASE_SHA256 = "3b420376331e918b4c864e9b37937ef35fd9f49066b8d6402e44aae9da598db2"
BASE_PPR_SHA256 = "84611fcb854deab5e9e7110aa7fdd68cfed25ba17d988231ab092c51a66b8fbc"


def generate_ppl() -> str:
    raw = BASE.read_bytes()
    if hashlib.sha256(raw).hexdigest() != BASE_SHA256:
        raise RuntimeError("v1.8 source changed; review the additive transformation")
    s = raw.decode("latin-1").replace("\r\n", "\n")

    def replace(old: str, new: str, count: int = 1) -> None:
        nonlocal s
        actual = s.count(old)
        if actual != count:
            raise RuntimeError(f"Expected {count} source anchors, found {actual}: {old[:100]!r}")
        s = s.replace(old, new)

    replace("FAST SPIN ECHO\n", """v1.81 additive candidate, 8 October 2026.
Generated by examples/build_v181_ppl.py; scanner verification required.
The first read prephase is moved after diffusion by signed area fusion.
RF waveform, duration, flip and slice width are unchanged.
The pre-read list window includes settling before channel selection.

FAST SPIN ECHO
""")
    replace("\tint t_flow, G1, G2;", """\tint t_flow, G1, G2;
\tint v181_first_read_dp, v181_read_dp;
""")
    # The same early backward stop hub used by the console-compatible v19
    # revisions removes the many far-forward exits without entering an if body.
    replace("\tphase_sign =  1;", """\tphase_sign =  1;
\tgoto v181_run;
end:
\tgoto v181_exit;
v181_run:
""")
    replace("\nend:\n\t\n}", "\nv181_exit:\n\t\n}")
    # Static rejections sit before the validate jump so the console validator
    # and the played sequence reject identically, before any RF. They use only
    # protocol parameters (diff_on, flow_comp_on, mtc_on). mtc_on is rejected
    # here, ahead of the first per-TR "if(mtc_on)" shell below.
    replace("#ifdef VALIDATOR\n\tif (validate==1)\n\t{\n\t\t/* [MERGE-2TE] M1 (port)", """\t// V181: the relocated read prephase is not a flow-compensated waveform.
\tif ((diff_on==1)&&(flow_comp_on!=0))
\t{ printf("V181 DWI requires flow compensation off\\n"); goto end; }
\tif (mtc_on!=0)
\t{ printf("V181 CEST/MTC not supported\\n"); goto end; }

#ifdef VALIDATOR
\tif (validate==1)
\t{
\t\t/* [MERGE-2TE] M1 (port)""")
    # Increase the old 18.5 us list window to 100 us, including 50 us channel
    # settling. Subtract the exact 81.5 us from all subsequent read balances.
    replace("te_balance_bl_temp1 = te_balance_bl*10L - 210L;",
            "te_balance_bl_temp1 = te_balance_bl*10L - 210L - 815L;")
    replace("te_balance_bl_temp1_esp = te_balance_bl_esp*10L - 210L - 36L;",
            "te_balance_bl_temp1_esp = te_balance_bl_esp*10L - 210L - 36L - 815L;")
    replace("/*  Calculate phase increment following each 180 degree pulse */", """\t// V181: reject a read-balance deficit before the first RF.
\tif ((diff_on==0)&&(te_balance_bl_temp1<=25L))
\t{ printf("V181 ESP leaves no read balance\\n"); goto end; }
\tif ((diff_on==1)&&(views_per_seg>1)&&(te_balance_bl_temp1_esp<=25L))
\t{ printf("V181 ESP leaves no train read balance\\n"); goto end; }

/*  Calculate phase increment following each 180 degree pulse */
""")
    # The relocation scale/DAC/slew guards need only gr_dp and grp_dp (final
    # after the flow-comp block) and protocol parameters, so they run just
    # before the validate exit: on both paths and before any RF. The block
    # moved as a whole (guards and the scale() result), so the arithmetic is
    # not duplicated; templ1/templ2 are rewritten before their next use.
    replace("\t\tgrp_dp = -gr_flow;\n\t}\n\t\n#ifdef VALIDATOR\n", """\t\tgrp_dp = -gr_flow;
\t}
\t
\t// V181: an RF conjugates the old negative read prephase. Play its
\t// positive equivalent in the first read-list prelude after diffusion.
\t// Both use the same secondary ramp samples; only the plateau changes.
\t// Checked before the validate exit so validate and played paths agree.
\tv181_first_read_dp=gr_dp;
\tif (diff_on==1)
\t{
\t\ttempl1=IntToLong(grp_dp)*(IntToLong(tref)+IntToLong(tramp));
\t\ttempl1=templ1/(IntToLong(tdp)+IntToLong(tramp));
\t\tif ((templ1<-32767L)||(templ1>32767L))
\t\t{ printf("V181 read relocation scale outside DAC\\n"); goto end; }
\t\ttempl2=IntToLong(gr_dp)-templ1;
\t\tif (templ2<0L) templ2=0L-templ2;
\t\tif ((templ2>32767L)||(templ2>IntToLong(crusher_max_dac)))
\t\t{ printf("V181 first read prephase exceeds DAC\\n"); goto end; }
\t\tif (templ2*100L>IntToLong(crusher_slew_dac_100us)*IntToLong(tramp))
\t\t{ printf("V181 first read prephase exceeds slew\\n"); goto end; }
\t\tv181_first_read_dp=gr_dp-scale(grp_dp,tref+tramp,tdp+tramp);
\t}

#ifdef VALIDATOR
""")
    replace("\tG1 = grp_dp; /* if flow_comp_on = 0 */", """\tG1 = grp_dp; /* if flow_comp_on = 0 */
\tif (diff_on==1) G1=0;
""")
    replace("\t\tCREATE_MATRIX(aq_mat_sec,gs_on*(gsp_rp-(gp_sl_var*gp_sl_on*nav_cnt)), gp_on*gp_var, gr_on*gr_dp)", """\t\tv181_read_dp=gr_dp;
\t\tif ((diff_on==1)&&(total_echo_cnt==0))
\t\t\tv181_read_dp=v181_first_read_dp;
\t\tCREATE_MATRIX(aq_mat_sec,gs_on*(gsp_rp-(gp_sl_var*gp_sl_on*nav_cnt)), gp_on*gp_var, gr_on*v181_read_dp)
""")
    replace("\t\ttemp = 0;\n\t\tif(total_echo_cnt == 0) \n\t\t\ttemp = post_180_delay_1;", """\t\t// V181: allow the previous slice list to finish before selection.
\t\tdelay(50,us);
\t\ttemp = 0;
\t\tif(total_echo_cnt == 0)
\t\t\ttemp = post_180_delay_1;
""")
    replace("\twaittimer(210 + temp - 25); // 25 is the time taken by if statement before delay32 below",
            "\twaittimer(1000); // V181 fixed 100 us window; balances subtract 815 ticks")
    # These are actual enlarged pre-RF windows, not relaxed guard thresholds.
    # The matching TR minimum subtracts their added 895 us from the idle delay.
    replace("\twaittimer(5300);", "\twaittimer(6500); // V181 timing calculation window")
    replace("\t\ttempl1 = 37500L;", "\t\ttempl1 = 42500L;")
    replace("\t\ttempl1 = 27500;", "\t\ttempl1 = 32500;")
    replace("\ttempl1 = templ1 + 11350L + 70L + 69L;",
            "\ttempl1 = templ1 + 12245L + 70L + 69L;")
    replace("// 113500 ticks (11350 us) = 31000+5300+19700+27500+30000 waittimer above and below",
            "// V181 fixed setup: 31000+6500+19700+32500+32750 = 122450 ticks")
    replace("crusher_setup_ticks>24500", "crusher_setup_ticks>27250")
    replace("\twaittimer(30000); // 3000 us; included in the 11350-us TR overhead",
            "\twaittimer(32750); // V181 3275 us, with 550 us check reserve")
    replace("// Reserve 550 us for timer/check overhead within the 3000 us setup window.",
            "// V181 reserves 550 us within the 3275 us setup window.")
    # Image compaction (no-growth gate vs v1.8): compile out the CEST/MTC
    # feature. Every repository protocol has mtc_on=0. Its unconditional
    # setup assignments (incl. rwt[17]) stay; the list, matrix, TR term,
    # frequency setup and pulse loop were reachable only with mtc_on!=0,
    # which is now rejected before RF where v1.8 checked the CEST delay.
    replace("#define MTC\n", "")
    replace("#ifdef MTC\t\n\ttselmtcl = IntToLong(tselmtc_ms)*1000L;",
            "\ttselmtcl = IntToLong(tselmtc_ms)*1000L;")
    replace("\trwt[mtc_rfnum] = tselmtc_ms*10; \t// 1000 is the number of points in the frame\n#endif\t\n",
            "\trwt[mtc_rfnum] = tselmtc_ms*10; \t// 1000 is the number of points in the frame\n")
    # Keep the unconditional (dead) CEST TR-term expression so the untimed
    # per-TR statement cost, and therefore event timing, is unchanged.
    line = next(x for x in s.split("\n") if x.startswith("\ttempl1 = (no_cest_pulses*tselmtcl"))
    note = "\t// Calculate the inter-CEST-pulse delay \n"
    replace("#ifdef MTC\n" + line + "\n" + note, line + "\n" + note + "#ifdef MTC\n")
    # Likewise keep each per-TR "if(mtc_on){ }" test, but as a shell whose only
    # statement is "goto end;" (no empty body: no compiled precedent). It is
    # unreachable, since mtc_on!=0 is rejected before the validate jump, and
    # "end:" is the early backward hub (no forward goto). Only the bodies,
    # reachable solely with mtc_on!=0, are compiled out.
    lines = s.split("\n")
    shells = 0
    for i in range(len(lines) - 1):
        if lines[i] == "#ifdef MTC" and lines[i + 1].strip() == "if(mtc_on){":
            depth, j = 0, i
            while True:
                if lines[j].startswith("#if"):
                    depth += 1
                elif lines[j].startswith("#endif"):
                    depth -= 1
                    if depth == 0:
                        break
                j += 1
            k = j - 1
            while lines[k].strip() == "":
                k -= 1
            if lines[k].strip() != "}":
                raise RuntimeError("Unexpected MTC block closing")
            lines[i], lines[i + 1] = lines[i + 1], "\t\tgoto end;\n#ifdef MTC"
            lines[k], lines[j] = lines[j].rstrip(), lines[k]
            shells += 1
    if shells != 3:
        raise RuntimeError(f"Expected three if(mtc_on) shells, found {shells}")
    s = "\n".join(lines)
    if s.count("#ifdef MTC") != 5:
        raise RuntimeError("Expected five remaining MTC-only blocks")
    return s


def generate_ppr() -> str:
    raw = BASE_PPR.read_bytes()
    if hashlib.sha256(raw).hexdigest() != BASE_PPR_SHA256:
        raise RuntimeError("Acquired test1e protocol changed; review provenance")
    s = raw.decode("latin-1").replace("\r\n", "\n")
    if s.count("FSE_dwi_CPMG_non_CPMG_twoTE-1.8.ppl") != 1:
        raise RuntimeError("Expected one test1e sequence reference")
    return s.replace("FSE_dwi_CPMG_non_CPMG_twoTE-1.8.ppl", PPL.name)


def build() -> dict[str, str]:
    result = {}
    for path, text in ((PPL, generate_ppl()), (PPR, generate_ppr())):
        data = text.replace("\n", "\r\n").encode("latin-1")
        path.write_bytes(data)
        result[str(path.relative_to(ROOT))] = hashlib.sha256(data).hexdigest()
    return result


if __name__ == "__main__":
    for path, digest in build().items():
        print(digest, path)
